### ISSUE TITLE
Outage on quay.io Container Registry 

### ISSUE THREAD

**Issue by abstractmachines** [alexgervais/status#11]
The Quay.io registry is experiencing degraded performance. If you are experiencing issues using quay.io/datawire, we encourage you to switch to docker.io/datawire  or gcr.io/datawire. See https://status.quay.io/ for more information:

Quay.io image pulls failing with the code "502 Bad Gateway". Engineers are currently investigating.

**Comment by khussey** [comment]
Red Hat fixed the issue with Quay.io as of 1am EDT on March 23. This incident is now resolved.
