### ISSUE TITLE
registry-1.docker.io is not responding

### ISSUE THREAD

**Issue by isc-gsaito** [alexgervais/status#23]
Browser requests to https://registry-1.docker.io are returning a 404 error message. 

Ping commands to registry-1.docker.io are not getting responses, 100% packet loss. 

My DNS server is resolving registry-1.docker.io to the following addresses: 

Non-authoritative answer:
Name:   registry-1.docker.io
Address: 3.216.34.172
Name:   registry-1.docker.io
Address: 34.205.13.154
Name:   registry-1.docker.io
Address: 44.205.64.79

Can someone take a look at this ?

**Comment by alexgervais** [comment]
Closing this issue as it is unrelated to Ambassador Labs & Datawire. Feel free to re-open it in a more suited repository.
